#! /usr/bin/env bash

# Determine which command is available to render the file
render_command='cat'
if command -v mdcat > /dev/null; then
  render_command='mdcat'
elif command -v bat > /dev/null; then
  render_command='bat'
fi

file_to_render="$1"
if [[ -z $1 ]]; then
  # location based on XDG directory specification
  # ref - https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
  notes_path="${XDG_DATA_HOME:-$HOME/.local/share}/totes"

  if [[ ! -d $notes_path ]]; then
    echo "The notes directory - $notes_path - does not exist."
    # shellcheck disable=2016
    echo 'Try running the `install.sh` script again'
    # checks if this script is in a repo (should be true if it is symlinked)
    if git rev-parse HEAD > /dev/null 2>&1; then
      # display full path to install script if we can find it
      echo "path: $(git rev-parse --show-toplevel)/install.sh"
    fi
    exit 1
  fi

  # ref - https://github.com/koalaman/shellcheck/issues/1247
  # shellcheck disable=2012
  file_to_render="$(ls -At -- "$notes_path"/*.md | tail -n 1)"
  # update last read time to cycle through notes
fi

echo
"$render_command" "$file_to_render"
echo

printf "%s" " --> (n)ext, (q)uit, (x) save and quit "
read -r -s -n 1 user_action < /dev/tty

# ref - https://stackoverflow.com/a/37408702
if ! [[ "$user_action" =~ ^(x|X)$ ]]; then
  touch "$file_to_render"
fi
echo
case $user_action in
  n | N)
    totes
    ;;
  x | X) ;;

  *) ;;

esac
