name: shfmt

on: [push]

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install `shfmt`
        run: sudo snap install shfmt
      - name: Run `shfmt`
        run: ./infra/actions/shfmt
